security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:


        in_memory:
            memory:
                users:
                    admin: { password: 123, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: /admin/
            logout:
                path:   logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }